In [1]:
import subprocess
import os
import csv
import pandas as pd
from tqdm import tqdm

# Define the parameters and the values to try

In [2]:
os.chdir("C:/Users/ed/Development/dhzw/8-sensitivity-analysis")

In [3]:
# Open the CSV file and read it as a list of dictionaries
with open('data/alpha_labels.csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    alphas = [row['parameter'] for row in reader]
    
df_baseline = pd.read_csv('data/baseline_parameters.csv', index_col=False)

In [4]:
# Define the range of values for each parameter
values = [-10.0, -8.0, -6.0, -4.0, -2.0, 0.0, 2.0, 4.0, 6.0, 8.0, 10.0]

# Create the entier parameter sets

In [5]:
# Create an empty table with the column headers from params
table = df_baseline.transpose()

table.columns = table.iloc[0]
table = table[1:]

table['used_parameter_label'] = 0
table['used_parameter_value'] = 0

table

parameter,alphaWalk,alphaBike,alphaCarDriver,alphaCarPassenger,alphaBus,alphaTrain,betaTimeWalk,betaTimeBike,betaTimeCarDriver,betaTimeCarPassenger,betaTimeBus,betaTimeTrain,betaCostCarDriver,betaCostCarPassenger,betaCostBus,betaCostTrain,betaTimeWalkTransport,betaChangesTransport,used_parameter_label,used_parameter_value
baseline_value,0.0,0.0,0.0,0.0,0.0,0.0,-0.04,-0.03,-0.02,-0.02,-0.02,-0.02,-0.15,-0.15,-0.1,-0.1,-0.03,-0.3,0,0

In [6]:
# create a dataframe with all the entire parameter sets. replace the alpha value to analyse

for alpha in alphas:
    for value in values:
        # Create a new row based on the baseline
        new_row = table.iloc[0].copy()
        
        # set the alpha value to try
        new_row['used_parameter_label'] = alpha
        new_row['used_parameter_value'] = value
        new_row[alpha] = value
        new_row['carCostKm'] = 0.25
        new_row['ptCostKm'] = 0.187
        new_row["ptBaseCost"] = 1.08

        # add the new row
        table = pd.concat([table, new_row.to_frame().T], ignore_index=True)
     
    
# remove the baseline
table = table.iloc[1:]

table

parameter,alphaWalk,alphaBike,alphaCarDriver,alphaCarPassenger,alphaBus,alphaTrain,betaTimeWalk,betaTimeBike,betaTimeCarDriver,betaTimeCarPassenger,...,betaCostCarPassenger,betaCostBus,betaCostTrain,betaTimeWalkTransport,betaChangesTransport,used_parameter_label,used_parameter_value,carCostKm,ptCostKm,ptBaseCost
1,-10.0,0.0,0.0,0.0,0.0,0.0,-0.04,-0.03,-0.02,-0.02,...,-0.15,-0.1,-0.1,-0.03,-0.3,alphaWalk,-10.0,0.25,0.187,1.08
2,-8.0,0.0,0.0,0.0,0.0,0.0,-0.04,-0.03,-0.02,-0.02,...,-0.15,-0.1,-0.1,-0.03,-0.3,alphaWalk,-8.0,0.25,0.187,1.08
3,-6.0,0.0,0.0,0.0,0.0,0.0,-0.04,-0.03,-0.02,-0.02,...,-0.15,-0.1,-0.1,-0.03,-0.3,alphaWalk,-6.0,0.25,0.187,1.08
4,-4.0,0.0,0.0,0.0,0.0,0.0,-0.04,-0.03,-0.02,-0.02,...,-0.15,-0.1,-0.1,-0.03,-0.3,alphaWalk,-4.0,0.25,0.187,1.08
5,-2.0,0.0,0.0,0.0,0.0,0.0,-0.04,-0.03,-0.02,-0.02,...,-0.15,-0.1,-0.1,-0.03,-0.3,alphaWalk,-2.0,0.25,0.187,1.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,0.0,0.0,0.0,0.0,0.0,2.0,-0.04,-0.03,-0.02,-0.02,...,-0.15,-0.1,-0.1,-0.03,-0.3,alphaTrain,2.0,0.25,0.187,1.08
63,0.0,0.0,0.0,0.0,0.0,4.0,-0.04,-0.03,-0.02,-0.02,...,-0.15,-0.1,-0.1,-0.03,-0.3,alphaTrain,4.0,0.25,0.187,1.08
64,0.0,0.0,0.0,0.0,0.0,6.0,-0.04,-0.03,-0.02,-0.02,...,-0.15,-0.1,-0.1,-0.03,-0.3,alphaTrain,6.0,0.25,0.187,1.08
65,0.0,0.0,0.0,0.0,0.0,8.0,-0.04,-0.03,-0.02,-0.02,...,-0.15,-0.1,-0.1,-0.03,-0.3,alphaTrain,8.0,0.25,0.187,1.08
66,0.0,0.0,0.0,0.0,0.0,10.0,-0.04,-0.03,-0.02,-0.02,...,-0.15,-0.1,-0.1,-0.03,-0.3,alphaTrain,10.0,0.25,0.187,1.08

In [7]:
#Save the table
table.to_csv('data/parametersets_to_run.csv', index=False)